.honey:front:build:docker:dev:
  stage: build:docker
  image:
    name: ${KANIKO_EXECUTOR_IMAGE}
    entrypoint: ['']
  only:
    - dev
  variables:
    IS_DEV: ${IS_DEV}
    REACT_APP_ENV: ${REACT_APP_ENV}
  before_script:
    - export VAULT_ADDR=${VAULT_DEV_SERVER_URL}
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=honey-frontend-docker jwt=$CI_JOB_JWT)"
    - vault status
    - export AWS_CREDS="$(vault kv get -field=AWS_JSON humandone/docker-dev/AWS | base64 -d)"
    - export AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r .accessKeyId)
    - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r .secretAccessKey)
  script:
    - echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_ACCOUNT_ID.dkr.ecr.region.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $DOCKER_CONTEXT --dockerfile $DOCKERFILE_LOCATION
      --build-arg IS_DEV=${IS_DEV}
      --build-arg REACT_APP_ENV=${REACT_APP_ENV}
      --destination $DOCKER_IMAGE

.honey:front:build:docker:prod:
  stage: build:docker
  image:
    name: ${KANIKO_EXECUTOR_IMAGE}
    entrypoint: ['']
  only:
    - master
  variables:
    IS_DEV: ${IS_DEV}
    REACT_APP_ENV: ${REACT_APP_ENV}
  before_script:
    - export VAULT_ADDR=${VAULT_DEV_SERVER_URL}
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=honey-frontend-docker jwt=$CI_JOB_JWT)"
    - vault status
    - export AWS_CREDS="$(vault kv get -field=AWS_JSON humandone/docker-dev/AWS | base64 -d)"
    - export AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r .accessKeyId)
    - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r .secretAccessKey)
  script:
    - echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_ACCOUNT_ID.dkr.ecr.region.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $DOCKER_CONTEXT --dockerfile $DOCKERFILE_LOCATION
      --build-arg IS_DEV=${IS_DEV}
      --build-arg REACT_APP_ENV=${REACT_APP_ENV}
      --destination $DOCKER_IMAGE
